---
- hosts: all
  connection: local

  roles:
#    - { role: cmprescott.chrome, become: yes}
    - git-setup
    - symlink-setup

  vars:
    home: /home/amkirby
    # git_home: /home/amkirby/Git
    font_home: /home/amkirby/.local/share/fonts
    distro_vars: distro_vars

  tasks:

    - name: include application var
      include_vars: '{{ distro_vars}}/{{ ansible_distribution }}.yml' #"{{ item }}"
      # with_first_found:
      #   - '{{ distro_vars}}/{{ ansible_distribution }}.yml'

    #- name: look at vars
    #  debug:
    #    var: applications

    # ====================
    #      For Ubuntu
    # ====================
    - name: create local fonts directory
      file:
        path: '{{ font_home }}/adobe-fonts/source-code-pro'
        state: directory

    - name: clone adobe source-code-pro font
      git:
        repo: https://github.com/adobe-fonts/source-code-pro.git
        dest: '{{ font_home }}/adobe-fonts/source-code-pro'
        version: release
      notify: update font cache
   # ========================
   #      END For Ubuntu
   # ========================

    - name: Install packages
      apt: name={{ item }} state=installed
      with_items: "{{ applications }}"
      become: yes
      become_user: root

    - name: change shell
      shell: chsh -s /usr/bin/zsh amkirby
      become: yes
      become_user: root

  handlers:

    - name: update font cache
      command: fc-cache -f -v
