---
# vars file for polybar-setup
dependencies:
  # =============================
  #      Ubuntu Dependencies     
  # =============================
  # required dependencies
  - build-essential
  - git
  - cmake
  - cmake-data
  - pkg-config
  - libcairo2-dev
  - libxcb1-dev
  - libxcb-util0-dev
  - libxcb-randr0-dev
  - libxcb-composite0-dev
  - python-xcbgen
  - xcb-proto
  - libxcb-image0-dev
  - libxcb-ewmh-dev
  - libxcb-icccm4-dev
  #optional dependencies
  - libxcb-xkb-dev
  - libxcb-xrm-dev
  - libxcb-cursor-dev
  - libasound2-dev
  - libpulse-dev
  - i3-wm
  - libjsoncpp-dev
  - libmpdclient-dev
  - libcurl4-openssl-dev
  - libnl-genl-3-dev
  # =============================
  #      Fedora Dependencies     
  # =============================
  # required dependencies
  - cairo-devel
  - xcb-util-devel
  - libxcb-devel
  - xcb-proto
  - xcb-util-image-devel
  - xcb-util-wm-devel
  #optional dependencies
  - xcb-util-xrm-devel
  - xcb-util-cursor-devel
  - alsa-lib-devel
  - pulseaudio-libs-devel
  - i3-ipc
  - jsoncpp-devel
  - libmpdclient-devel
  - libcurl-devel
  - libnl3-devel
