---
# tasks file for symlink-setup
- name: Symlink dotfiles
  file: path={{ home }}/{{ item }} src={{ git_home }}/dotfiles/{{ item }} state=link
  with_items:
    - .Xresources
    - .zshrc

- name: Symlink i3 and conky
  file: path={{ home }}/.{{ item }} src={{ git_home }}/dotfiles/{{ item }} state=link
  with_items:
    - i3
    - conky

- name: Symlink Emacs config
  file: path={{ home }}/{{ item }} src={{ git_home }}/Emacs/{{ item }} state=link
  with_items:
    - .emacs
    - .emacs.d

- name: Symlink Vim config
  file: path={{ home }}/{{ item }} src={{ git_home }}/Vim/{{ item }} state=link
  with_items:
    - .vim
    - .vimrc

- name: Symlink polybar
  file: path={{ home }}/.config/{{ item }} src={{ git_home }}/dotfiles/{{ item }} state=link
  with_items:
    - polybar
    
- name: clone my oh-my-zsh
  git: repo=https://github.com/amkirby/oh-my-zsh.git dest={{ home }}/.oh-my-zsh

- name: clone zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ home }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    
